from .llama3_integration import Llama3Analyzer
from .whisper_transcriber import WhisperTranscriber
import spacy

class FeedbackAnalyzer:
    def __init__(self):
        self.llm = Llama3Analyzer()  # Llama3 for feedback generation
        self.transcriber = WhisperTranscriber(model_name="base")  # Whisper for transcription
        self.nlp = spacy.load("en_core_web_sm")  # spaCy for linguistic analysis

    def _get_spacy_stats(self, text: str) -> dict:
        """Calculate spaCy statistics for the given text."""
        try:
            doc = self.nlp(text)
            tokens = [{"text": token.text, "pos": token.pos_} for token in doc]
            entities = [{"text": ent.text, "label": ent.label_} for ent in doc.ents]
            readability = {
                "flesch_reading_ease": doc._.flesch_reading_ease if hasattr(doc._, "flesch_reading_ease") else None,
                "avg_sentence_length": sum(len(sent) for sent in doc.sents) / len(list(doc.sents)) if len(list(doc.sents)) > 0 else 0
            }
            sentiment = {
                "polarity": doc._.polarity if hasattr(doc._, "polarity") else None,
                "subjectivity": doc._.subjectivity if hasattr(doc._, "subjectivity") else None
            }
            return {
                "num_tokens": len(doc),
                "tokens": tokens,
                "named_entities": entities,
                "readability": readability,
                "sentiment": sentiment
            }
        except Exception as e:
            return {"error": f"Error calculating spaCy stats: {str(e)}"}
        
        def compare_transcriptions(self, speech_text: str, expected_text: str) -> dict:
            """
            Compare the transcribed speech text with the expected text.

            Args:
                speech_text (str): The transcribed speech text.
                expected_text (str): The expected text.

            Returns:
                dict: A dictionary containing discrepancies such as missing or extra words.
            """
            try:
                speech_words = set(speech_text.split())
                expected_words = set(expected_text.split())

                missing_words = expected_words - speech_words
                extra_words = speech_words - expected_words

                return {
                    "missing_words": list(missing_words),
                    "extra_words": list(extra_words),
                }
            except Exception as e:
                return {"error": f"Error comparing transcriptions: {str(e)}"}

    def analyze_feedback(self, speech_text: str, spacy_stats: dict, expected_text: str = None) -> dict:
        """
        Generate feedback based on the speech text, spaCy statistics, and expected text.

        Args:
            speech_text (str): The transcribed speech text.
            spacy_stats (dict): Linguistic statistics generated by spaCy.
            expected_text (str, optional): The expected text for comparison.

        Returns:
            dict: A dictionary containing feedback, discrepancies, and other details.
        """
        try:
            # Step 1: Compare speech_text with expected_text if provided
            discrepancies = None
            if expected_text:
                discrepancies = self.compare_transcriptions(speech_text, expected_text)
                print(f"Discrepancies between transcription and expected text: {discrepancies}")

            # Step 2: Generate feedback using Llama3
            prompt = (
                f"Speech: {speech_text}\n\n"
                f"Expected Text: {expected_text}\n\n"
                f"spaCy Stats: {spacy_stats}\n\n"

                "Analyze this speech and provide feedback on pronunciation, tone, and clarity. "
                "Suggest areas for improvement and practical exercises."
                "If there are discrepancies between the speech and expected text, highlight them."
                "The feedback should be elaborated but concise."
                "Limit your response in every aspect after the ai feedback to 20 words. for example if the ai feedback has 20 words"
                
                
                
                

            )
            feedback = self.llm.analyze(prompt)

            # Step 3: Return the feedback and discrepancies
            return {
                "speech_text": speech_text,
                "expected_text": expected_text,
                "discrepancies": discrepancies,
                "spacy_stats": spacy_stats,
                "feedback": feedback,
            }
        except Exception as e:
            return {"error": f"Error generating feedback: {str(e)}"}
        
    def generate_script(self, lessonPrompt: str, topic: str, min_words: int = 5, max_words: int = 20) -> str:
        """
        Generate a script based on the given lessonPrompt and topic using Llama3.
        Enforce a minimum and maximum word count, and limit the script to one paragraph.

        Args:
            lessonPrompt (str): The lesson-specific instruction for the script.
            topic (str): The topic for the script.
            min_words (int): The minimum number of words required in the script.
            max_words (int): The maximum number of words allowed in the script.

        Returns:
            str: The generated script.
        """
        try:
            # Log the values of lessonPrompt and topic
            print(f"Generating script with the following parameters:")
            print(f"Lesson Prompt: {lessonPrompt}")
            print(f"Topic: {topic}")
            print(f"Min Words: {min_words}")
            print(f"Max Words: {max_words}")

            # Construct the dynamic prompt
            prompt = (
                f"{lessonPrompt} {topic}\n\n"
                f"The script should be between {min_words} and {max_words} words long. "
                "Do not include any introductory or explanatory text. Only provide the script content."
                "Provide the Script only, no other introductory or explanatory text."
            )

            # Log the constructed prompt
            print(f"Constructed Prompt: {prompt}")

            # Generate the script using Llama3
            script = self.llm.analyze(prompt)

            # Split the script into paragraphs
            paragraphs = script.split("\n\n")
            first_paragraph = paragraphs[0].strip()  # Take the first paragraph

            # Ensure the script meets the minimum and maximum word count
            word_count = len(first_paragraph.split())
            if word_count < min_words:
                raise ValueError(
                    f"The generated script does not meet the minimum word count of {min_words} words."
                )
            if word_count > max_words:
                # Truncate the script to the maximum word count
                truncated_script = " ".join(first_paragraph.split()[:max_words]) + "..."
                print(f"Truncated Script: {truncated_script}")
                return truncated_script

            print(f"Generated Script: {first_paragraph}")
            return first_paragraph
        except Exception as e:
            print(f"Error generating script: {str(e)}")
            raise Exception(f"Error generating script: {str(e)}")
            
    def process_audio(self, audio_path: str, expected_text: str = None) -> dict:
        """
        Process the audio file and return transcription, spaCy stats, and feedback.

        Args:
            audio_path (str): The path to the audio file.
            expected_text (str, optional): The expected text for comparison.

        Returns:
            dict: A dictionary containing transcription, spaCy stats, feedback, and discrepancies.
        """
        try:
            # Step 1: Transcribe audio to text
            transcribed_text = self.transcriber.transcribe(audio_path)

            # Step 2: Calculate spaCy statistics
            spacy_stats = self._get_spacy_stats(transcribed_text)

            # Step 3: Generate feedback
            return self.analyze_feedback(transcribed_text, spacy_stats, expected_text)
        except Exception as e:
            return {"error": f"Error processing audio: {str(e)}"}
            
        